-d J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\ETHENET\ethernet_g\impl\synthesize\rev_1\Gbit_PHY_test_RGMII.vm
-p GW2A-18-PBGA484-7
-pn GW2A-LV18PG484C7/I6
-cst J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\ETHENET\ethernet_g\src\Gbit_PHY_test_RGMII.cst
-cfg J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\ETHENET\ethernet_g\impl\pnr\device.cfg
-sdc J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\ETHENET\ethernet_g\src\Gbit_PHY_test_RGMII.sdc
-gao J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\ETHENET\ethernet_g\impl\gao\gao.v
-bit
-tr
-ph
-posp
-reg_not_in_iob
