-d E:\gowin\DSI_colorbar\DSI_colorbar_test18K\DSI_colorbar_test\impl\synthesize\rev_1\sytech_lvds2mipi.vm
-p GW2A-18-PBGA484-8
-pn GW2A-LV18PG484C8/I7
-cst E:\gowin\DSI_colorbar\DSI_colorbar_test18K\DSI_colorbar_test\src\ivideo_dynamic.cst
-cfg E:\gowin\DSI_colorbar\DSI_colorbar_test18K\DSI_colorbar_test\impl\pnr\device.cfg
-bit
-tr
-ph
-timing
