-d J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\HDMI\Gowin_DVI_RXTX_RefDesign\project\impl\synthesize\rev_1\dk_video.vm
-p GW2A-18-PBGA484-8
-pn GW2A-LV18PG484C8/I7
-cst J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\HDMI\Gowin_DVI_RXTX_RefDesign\project\src\dk_video.cst
-cfg J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\HDMI\Gowin_DVI_RXTX_RefDesign\project\impl\pnr\device.cfg
-sdc J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\HDMI\Gowin_DVI_RXTX_RefDesign\project\src\dk_video.sdc
-gao J:\Source_bac\Gowin_board\GW2A_LV18PG484\gowin\HDMI\Gowin_DVI_RXTX_RefDesign\project\src\gao.v
-bit
-tr
-ph
-timing
